@echo off

echo Launching MCP in new cmd window...
start "MCP Server" cmd.exe /k "cd /d D:\project\bcons\Backend\mcp && call D:\project\myenv\Scripts\activate.bat && python run.py"

echo Launching Agent in new cmd window...
start "Agent Server" cmd.exe /k "cd /d D:\project\bcons\Backend\agent && call D:\project\myenv\Scripts\activate.bat && python run.py"

echo Launching Redis CLI in new cmd window...
start "Redis CLI" cmd.exe /k "cd /d D:\project\redis-win-3.0.504\redis-win-3.0.504\src && redis-cli.exe"

echo Launching Frontend in new cmd window...
start "Frontend" cmd.exe /k "cd /d D:\project\bcons\Frontend && call D:\project\myenv\Scripts\activate.bat && python run.py"
